# Generated by Django 4.0.3 on 2022-04-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productitem_alter_cart_products_productitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='user',
        ),
    ]
